-- JDT-17-LOYALTY Seed Data (DEPRECATED)
-- This file is superseded by Flyway migrations V2-V5.
-- Kept for reference only.
--
-- Active migrations:
--   V2__seed_partners.sql
--   V3__seed_exchange_rates.sql
--   V4__seed_rewards.sql
--   V5__seed_demo_members.sql
--
-- To apply seed data, run: mvn flyway:migrate
-- Or via Docker: docker-compose up backend (Flyway auto-runs on startup)
--
-- Raw API keys (for reference, hashed in V2):
--   KFC: kfc_api_key_2026_secure_demo_only
--   McD: mcd_api_key_2026_secure_demo_only
--
-- Credentials:
--   Admin: admin@jdt17loyalty.com / Admin123!
--   Member: budi.santoso@example.com / Member123!
